// TwentyfourData.js
const placementData = [
    {
      id: 1,
      companyName: "Moschip Technologies",
      recruitmentDate: "21/22/Sep/2023",
      cse: "-",
      it: "-",
      ece: "1",
      eee: "-",
      mech: "-",
      met: "-",
      civil: "-",
      te: "-",
      ssp: "-",
      ds: "-",
      adps: "-",
      mst: "-",
      mca: "1",
      totalSelects: "1",
      packages: "6 LPA",
      sector: "NON IT",
    },
    {
      id: 2,
      companyName: "L&T Constructions",
      recruitmentDate: "24-Sep-23",
      cse: "-",
      it: "-",
      ece: "-",
      eee: "-",
      mech: "22",
      met: "-",
      civil: "4",
      te: "-",
      ssp: "-",
      ds: "-",
      adps: "-",
      mst: "-",
      mca: "-",
      totalSelects: "26",
      packages: "6 LPA to 6.25 LPA",
      sector: "NON IT",
    },
    {
      id: 3,
      companyName: "Pennant Technologies",
      recruitmentDate: "27-Nov-23",
      cse: "10",
      it: "7",
      ece: "1",
      eee: "-",
      mech: "-",
      met: "-",
      civil: "-",
      te: "-",
      ssp: "-",
      ds: "-",
      adps: "-",
      mst: "-",
      mca: "-",
      totalSelects: "18",
      packages: "4 LPA",
      sector: "IT",
    },
  ];
  
  export default placementData;
  